services:
  app:
    image: ghcr.io/astral-sh/uv:python3.12-bookworm
    container_name: mcp_server
    volumes:
      - .:/usr/src/app/mcp-server-tavily
    working_dir: /usr/src/app
    command: tail -f /dev/null
    environment:
      - PYTHONUNBUFFERED=1
      - TAVILY_API_KEY=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
      - SEARXNG_URL=http://searxng:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - search_network
    depends_on:
      - searxng

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080/
      - INSTANCE_NAME=SearXNG MCP
    volumes:
      - searxng_data:/etc/searxng
    networks:
      - search_network

volumes:
  searxng_data:

networks:
  search_network:
    driver: bridge
