# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM python:3.12-slim

# Install the project into /app
WORKDIR /app

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
ADD . /app

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/src

ENTRYPOINT ["python3", "server.py"]
